#parser: babel-eslint
parser: "@typescript-eslint/parser"

parserOptions:
    ecmaVersion: 2021
    sourceType: module
    ecmaFeatures:
        jsx: true

plugins:
    - react
    - react-hooks
#    - node

extends:
    - react-app
    - react-app/jest
    - eslint:recommended
    - plugin:react/jsx-runtime

rules:
    no-extra-semi: off
    no-unused-vars: off
    no-inner-declarations: off
    no-lone-blocks: off
    no-undef: off
    no-empty: off

    "@typescript-eslint/no-unused-vars": off
    "@typescript-eslint/no-unused-expressions": off

    # Avoid code that looks like two expressions but is actually one
    no-unexpected-multiline: error
    no-restricted-globals: off
    #no-shadow: error
    no-template-curly-in-string: error

    #
    # Good Practices
    #
    no-new: error

    # node/no-process-env: error
    # node/no-unsupported-features/es-syntax: off
    # node/no-missing-import: off
    # node/no-unpublished-import: off

    # node/no-missing-import: [error, {
    #     allowModules: [],
    #     resolvePaths: [__dirname, ".", "src"],
    #     tryExtensions: [".ts", ".tsx"]
    # }]    

    react/jsx-uses-react: error
    react/jsx-uses-vars: error

    react-hooks/exhaustive-deps: off

    # node/no-unsupported-features/node-builtins: off

env:
    browser: true
    node: false
