import {app, BrowserWindow, session} from 'electron';
import path from 'path';

import {theme_} from './theme';
import {initWorker} from './worker';

import * as Setup from './setup';

// This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

function parseBool(value: string | undefined, defaultValue = false) {
    if (value === undefined) return defaultValue;

    return (['true', 'false', true, false].includes(value) && JSON.parse(value)) || defaultValue;
}

export let mainWindow_: Electron.BrowserWindow | null = null;
let splashWindow_: Electron.BrowserWindow | null = null;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
    // eslint-disable-line global-require
    app.quit();
}

function createWindow() {
    let devTools = process.env.NODE_ENV !== 'production';
    //devTools = true
    devTools = true;

    process.env['ELECTRON_DISABLE_SECURITY_WARNINGS'] = 'true';

    mainWindow_ = new BrowserWindow({
        width: 1200,
        height: 800,
        title: Setup.appTitle,
        backgroundColor: theme_.backgroundColor,
        show: false,
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
            nodeIntegration: true,
            contextIsolation: false,
            devTools: devTools,
            webSecurity: false,
        },
    });

    mainWindow_.on('closed', () => {
        mainWindow_ = null;
        app.exit(0);
    });

    mainWindow_.once('ready-to-show', () => {
        splashWindow_.destroy();
        splashWindow_ = null;

        mainWindow_.show();
        mainWindow_.maximize();
    });

    splashWindow_ = new BrowserWindow({
        width: 500,
        height: 300,
        //transparent: true,
        frame: false,
        alwaysOnTop: true,
        backgroundColor: theme_.backgroundColor,
        webPreferences: {
            webSecurity: false,
        },
    });
    let splashHtml = `${__dirname}/splash.html`;

    //splashWindow_.loadFile(splashHtml)
    //splashWindow_.loadURL('/renderer/splash.html')
    //splashWindow_.loadFile('renderer/splash.html')
    splashWindow_.loadFile(splashHtml);
    splashWindow_.show();
    console.log('SPLASH HTML', splashHtml);
    splashWindow_.center();

    //console.debug(MAIN_WINDOW_WEBPACK_ENTRY);

    mainWindow_.menuBarVisible = false;

    mainWindow_.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

    //if (parseBool(process.env.REACT_APP_DEV_TOOLS)) {
    if (devTools) {
        mainWindow_.webContents.openDevTools();
    }

    //mainWindow_.maximize()
    //mainWindow_.menuBarVisible

    initWorker(mainWindow_);

    //splash.close();
    //mainWindow_.show();
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
    // Customize protocol to handle static resource.
    session.defaultSession.protocol.registerFileProtocol('static', (request, callback) => {
        const fileUrl = request.url.replace('static://', '');
        const filePath = path.join(app.getAppPath(), '.webpack/main', fileUrl);
        callback(filePath);
    });

    createWindow();
});

// Quit when all windows are closed.
app.on('window-all-closed', () => {
    // On OS X it is common for applications and their menu bar
    // to stay active until the user quits explicitly with Cmd + Q
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

app.on('activate', () => {
    // On OS X it"s common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (mainWindow_ === null) {
        createWindow();
    }
});

//app.on('
