arrowParens: always
bracketSameLine: false
bracketSpacing: false
trailingComma: es5
tabWidth: 4
printWidth: 120
useTabs: false
semi: true
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: true
endOfLine: lf

overrides:
  - files: '*.js'
    options:
      tabWidth: 2
  - files: '*.json'
    options:
      tabWidth: 2
  - files: '*.html'
    options:
      tabWidth: 2
