parser: "@typescript-eslint/parser"

env:
  browser: true
  es6: true
  node: true

rules:
  # Avoid code that looks like two expressions but is actually one
  no-unexpected-multiline: error
  no-restricted-globals: off
  #no-shadow: error
  no-template-curly-in-string: error


extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/electron
  - plugin:import/typescript
